//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TB_EMPLOYEE()
        {
            this.TB_ATTANDANCE = new HashSet<TB_ATTANDANCE>();
            this.TB_BENEFIT = new HashSet<TB_BENEFIT>();
            this.TB_DEPARTMENT1 = new HashSet<TB_DEPARTMENT>();
            this.TB_EMPLOYEE_PROJECT = new HashSet<TB_EMPLOYEE_PROJECT>();
            this.TB_EMPLOYEE_ROLE = new HashSet<TB_EMPLOYEE_ROLE>();
            this.TB_EMPLOYEE1 = new HashSet<TB_EMPLOYEE>();
            this.TB_LEAVE_MANAGEMENT = new HashSet<TB_LEAVE_MANAGEMENT>();
            this.TB_LEAVE_MANAGEMENT1 = new HashSet<TB_LEAVE_MANAGEMENT>();
            this.TB_PAYROLL = new HashSet<TB_PAYROLL>();
            this.TB_PERFOMANCE_EVALUATION = new HashSet<TB_PERFOMANCE_EVALUATION>();
            this.TB_PERFOMANCE_EVALUATION1 = new HashSet<TB_PERFOMANCE_EVALUATION>();
            this.TB_RECRUITMENT = new HashSet<TB_RECRUITMENT>();
            this.TB_TRANING_AND_DEVELOPMENT = new HashSet<TB_TRANING_AND_DEVELOPMENT>();
        }
    
        public int employee_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<System.DateTime> date_of_birth { get; set; }
        public Nullable<int> gender { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string address { get; set; }
        public Nullable<int> department_id { get; set; }
        public Nullable<int> job_position_id { get; set; }
        public Nullable<System.DateTime> date_of_joining { get; set; }
        public Nullable<int> employment_status { get; set; }
        public Nullable<int> supervisor_id { get; set; }
        public Nullable<System.DateTime> created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
        public Nullable<System.DateTime> terminations_date { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_ATTANDANCE> TB_ATTANDANCE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_BENEFIT> TB_BENEFIT { get; set; }
        public virtual TB_DEPARTMENT TB_DEPARTMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_DEPARTMENT> TB_DEPARTMENT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EMPLOYEE_PROJECT> TB_EMPLOYEE_PROJECT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EMPLOYEE_ROLE> TB_EMPLOYEE_ROLE { get; set; }
        public virtual TB_JOB_POSITION TB_JOB_POSITION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_EMPLOYEE> TB_EMPLOYEE1 { get; set; }
        public virtual TB_EMPLOYEE TB_EMPLOYEE2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LEAVE_MANAGEMENT> TB_LEAVE_MANAGEMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_LEAVE_MANAGEMENT> TB_LEAVE_MANAGEMENT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PAYROLL> TB_PAYROLL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PERFOMANCE_EVALUATION> TB_PERFOMANCE_EVALUATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_PERFOMANCE_EVALUATION> TB_PERFOMANCE_EVALUATION1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_RECRUITMENT> TB_RECRUITMENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TB_TRANING_AND_DEVELOPMENT> TB_TRANING_AND_DEVELOPMENT { get; set; }
    }
}
