//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_EMPLOYEE_PROJECT
    {
        public int employee_project_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public Nullable<int> project_id { get; set; }
        public Nullable<int> role_on_project { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual TB_EMPLOYEE TB_EMPLOYEE { get; set; }
        public virtual TB_PROJECTS TB_PROJECTS { get; set; }
    }
}
