//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_PAYROLL
    {
        public int payroll_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public int salary_month { get; set; }
        public int basic_salary { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<int> deductions { get; set; }
        public int net_salary { get; set; }
        public System.DateTime payment_date { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual TB_EMPLOYEE TB_EMPLOYEE { get; set; }
    }
}
