//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_RECRUITMENT
    {
        public int recruitment_id { get; set; }
        public Nullable<int> job_position_id { get; set; }
        public string candidate_name { get; set; }
        public System.DateTime application_date { get; set; }
        public Nullable<System.DateTime> interview_date { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> hired_employee_id { get; set; }
        public System.DateTime created_at { get; set; }
        public Nullable<System.DateTime> updated_at { get; set; }
    
        public virtual TB_EMPLOYEE TB_EMPLOYEE { get; set; }
        public virtual TB_JOB_POSITION TB_JOB_POSITION { get; set; }
    }
}
